In [79]:
import sys
import numpy as np

In [80]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [81]:
a=np.array([2,4,6,8,10])
b=np.array([1,3,5,7,9,11])

In [82]:
print(a)
print(b)


[ 2  4  6  8 10]
[ 1  3  5  7  9 11]


In [83]:
a[0]

2

In [84]:
a[4]

10

In [85]:
b[3]

7

In [86]:
b[[0,2,-1]]

array([ 1,  5, 11])

In [87]:
a[1:3]

array([4, 6])

In [88]:
b[:4]

array([1, 3, 5, 7])

In [89]:
import numpy as np

In [90]:
n = 3

In [91]:
2**n

8

In [92]:
120

120

In [93]:
x = 5

In [94]:
np.int8

numpy.int8

In [95]:
type(x)

int

In [96]:
a[::2] #Step of 2

array([ 2,  6, 10])

# Array Types

In [97]:
a

array([ 2,  4,  6,  8, 10])

In [98]:
b

array([ 1,  3,  5,  7,  9, 11])

In [99]:
type(a)

numpy.ndarray

In [100]:
id(a)

2088749623616

In [101]:
a.dtype

dtype('int32')

In [102]:
b.dtype

dtype('int32')

In [103]:
array([1,2,3,4],dtype=np.int8)

NameError: name 'array' is not defined

In [ ]:
d=np.array([{'a':1},sys])

In [ ]:
d

In [ ]:
d.dtype

# DIMENSION AND SHAPES

In [ ]:
A=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
A.shape

In [ ]:
A.shape

In [ ]:
A.ndim

In [ ]:
A.size

In [ ]:
B=np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [ ]:
B

In [ ]:
B.shape

In [ ]:
#Square matrix
A=np.array([
#    0,1,2
    [1,2,3], # 0 row
    [4,5,6], #1 row
    [7,8,9]  #2 row
]
)

In [ ]:
A

In [ ]:
A[1][0] # 1 row 0 columns


In [ ]:
A[1,0]

In [ ]:
A[0:2]

In [ ]:
A[:,:2]

In [ ]:
A[:2,:2]

In [ ]:
A[1]=np.array([10,10,10])

In [ ]:
A[1] #Only rows have been updated

In [ ]:
A[2]=99

In [ ]:
A[2]

In [ ]:
A

# SUMMARY STATISTICS

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std() #standard deviation is the square root of the variance

In [ ]:
a.var() #variance

In [ ]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
A.sum()


In [ ]:
A.var()

In [ ]:
A.mean()

In [ ]:
A.std() 

In [ ]:
A.sum(axis=0) #Axes are used to defined the 2 dimensions one is in the vertical downward and one is in the horizontal running acrosss the column                  

In [ ]:
A.sum(axis=1)

In [ ]:
A.mean(axis=0)   #Mean for the dimension 0 

In [ ]:
A.mean(axis=1) #Mean for the dimension 1

In [ ]:
A.std(axis=0)  #Standard deviation for the dimension 0

In [ ]:
A.std(axis=1) #Standard Deviation for the dimension 1

# Broadcasting and vectorized operations

In [ ]:
a=np.arange(10) # creating a array of 10 elements

In [ ]:
a

In [ ]:
a + 10 #Adding 10 to each element in the array 

In [ ]:
a*10 #Multiplying each element in the array

In [ ]:
a  #array 

In [ ]:
a +=10 # it means we are adding 10 to each element in array

In [ ]:
a

In [ ]:
a =10

In [ ]:
a

In [ ]:
a=np.arange(10)

In [104]:
a

array([ 2,  4,  6,  8, 10])

In [105]:
a += 10 #Here we are asking array to increase the  size of each element by 10 

In [106]:
a

array([12, 14, 16, 18, 20])

In [107]:
b=np.array([10,10,10,10]) #we are giving here the list of elements in the array if we use arange we have to give just the limit oh number like 4,5,6,7, etc

In [108]:
b

array([10, 10, 10, 10])

In [109]:
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
a=np.arange(4)

In [ ]:
a

In [ ]:
a+b

In [ ]:
a*b

# BOOLEAN ARRAYS Also called masks

In [ ]:
a=np.arange(4)

In [ ]:
a

In [ ]:
a[[0,-1]]

In [ ]:
a[[True,False,False,True]] #We are calling the elements with the respect to the index no.

In [ ]:
a>=2

In [ ]:
a[[False,False,True,False]]

In [ ]:
a[a>=2]

In [ ]:
a.mean()

In [ ]:
a[a>a.mean()]

In [ ]:
a[~(a > a.mean())]

In [110]:
a[(a == 0)|(a == 1)]

array([], dtype=int32)

In [111]:
a[(a<=2)&(a%2 == 0)]

array([], dtype=int32)

In [112]:
A=np.random.randint(100,size=(3,3)) #Here we are using random module to generate randint function to get random numbers from the given list

In [113]:
A

array([[89, 81, 35],
       [70, 43,  9],
       [12, 35, 98]])

In [114]:
A[np.array([
    [True,False,True],
    [False,True,False],
    [True,False,True]
])]

array([89, 35, 43, 12, 98])

In [115]:
A>30

array([[ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True]])

# Linear algebra 

In [116]:
import math
A=np.array([
    [1,2,3],
           [4,5,6],
           [7,8,9]
])
           

In [117]:
B=np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [118]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [119]:
A @ B #It does the same in the dot operation of the linear alebra


array([[20, 14],
       [56, 41],
       [92, 68]])

In [120]:
B.T #Here T is the transform matrix converting rows into columns and columns into rows

array([[6, 4, 2],
       [5, 3, 1]])

In [121]:
import scipy 
vdot(A,B)

NameError: name 'vdot' is not defined

In [ ]:
import scipy
import scipy.linalg as la

In [122]:
B.T@A # in this we are performing Transform matrix and then we are performing the dot operation

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in the memory

int,float

In [123]:
sys.getsizeof(1)

28

In [124]:
sys.getsizeof(10**100)

72

In [125]:
np.dtype(int).itemsize

4

In [126]:
a=6
b=7

In [127]:
string_var="Hello world"
also_a_string_var='Hello,World!'

In [128]:
c=a+b
print(c)

13


In [129]:
string = string_var + also_a_string_var

In [130]:
print(string)

Hello worldHello,World!


In [131]:
print(also_a_string_var,a,b)

Hello,World! 6 7


In [132]:
#Lists

empty_list=list()
also_empty_list=[]
zeros_list=[0] * 5
print(zeros_list)

[0, 0, 0, 0, 0]


In [133]:
empty_list.append(np.arange(10))
print(empty_list)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]


In [134]:
print(len(empty_list))

1


In [135]:
def add_numbers(a,b):
    return a+b

In [136]:
print(add_numbers(3,4))

7


In [137]:
#Lambda Function
lambda_add_numbers=lambda a,b:a+b
print(lambda_add_numbers(3,4))

7


In [138]:
#Looping
for i in range(5):
    print("Looping Fatima Khatoon")

Looping Fatima Khatoon
Looping Fatima Khatoon
Looping Fatima Khatoon
Looping Fatima Khatoon
Looping Fatima Khatoon


In [139]:
filled_list=[a/2 for a in range(10)]
print(filled_list)

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]


In [140]:
filled_dict={a:a**2 for a in range (5)}
print(filled_dict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


In [141]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [142]:
b=np.eye(2)

In [143]:
b

array([[1., 0.],
       [0., 1.]])

In [144]:
c=np.ones(2)

In [145]:
c

array([1., 1.])

In [146]:
d=np.full((2,2),7)

In [147]:
d

array([[7, 7],
       [7, 7]])

In [148]:
e=np.random.random((2,2))
print(e)

[[0.52429169 0.44534191]
 [0.62048413 0.4796716 ]]


In [149]:
sys.getsizeof([1])

64

In [150]:
np.array([1]).nbytes

4

In [151]:
l=list(range(100000))

In [152]:
a=np.arange(100)

In [153]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Useful Numpy Functions

# random


In [154]:
np.random.normal(size=2)

array([1.36502012, 0.59361997])

In [155]:
np.random.random(size=2)

array([0.66426184, 0.15934022])

# arange

In [156]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [158]:
np.arange(0,1,-1)

array([], dtype=int32)

# linspace

In [159]:
np.linspace(0,1,5) #linspace gives the distance that the numbers should have.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [160]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [161]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# reshape

In [162]:
np.arange(10).reshape(2,5) #Here we are asking to create an array of 2 rows and 3 columns with in the range of 10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# ZEROS,ONES,EMPTY

In [163]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [164]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [165]:
np.zeros((3,3),dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [166]:
np.empty(3)

array([1.03196282e-311, 0.00000000e+000, 1.61323711e-307])

In [167]:
np.empty((1,5))

array([[0., 0., 0., 0., 0.]])

In [168]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [169]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# identity and eye

In [170]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [171]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [172]:
np.eye(8,8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [173]:
np.eye(4,4,k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [174]:
"Hello World"[6]

'W'

# PANDAS

In [175]:
import pandas as pd
import numpy as np

We will start analyzing "The Group Of Seven".Which is political formed by Canada,Germany,Italy,Japan,the United Kingdom and the united states.We will start by analyzing population,and for that, we will use  a pandas.Series object.

In [176]:
g7_pop=pd.Series([35.467,63.951,80.940,60.665,127.061,64.511,318.523])

In [177]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
dtype: float64

In [178]:
g7_pop.name="GEOGRAPHICAL POPULATION"

In [179]:
g7_pop

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [180]:
g7_pop.dtype

dtype('float64')

In [181]:
g7_pop.shape

(7,)

In [182]:
g7_pop.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [183]:
type(g7_pop.values)

numpy.ndarray

In [184]:
g7_pop[0]

35.467

In [185]:
g7_pop.index

RangeIndex(start=0, stop=7, step=1)

In [186]:
l=['a','b','c']

In [187]:
g7_pop.index=[    #Here in this we have assgned the country names to the serial or the index number
    'Canada',
    'France',
    'Germany',
    'Italy' ,
    'Japan',
    'United Kingdom',
    'United States'
]

In [188]:
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [189]:
pd.Series(g7_pop,index=['France','Germany','Italy','Spain']) #Accessing the data from wrt country

France     63.951
Germany    80.940
Italy      60.665
Spain         NaN
Name: GEOGRAPHICAL POPULATION, dtype: float64

# Indexing

Index is similar to the list and dictionary,you used the index of the element u are looking for :


In [190]:
g7_pop["Canada"]

35.467

In [191]:
g7_pop["United Kingdom"]

64.511

# Numerical positins can also be used with attribute iloc

In [192]:
g7_pop.iloc[0]   #index location

35.467

In [193]:
g7_pop.iloc[-1]

318.523

In [194]:
#Selecting multiple elements at once 

g7_pop[["Italy","France","United Kingdom"]]

Italy             60.665
France            63.951
United Kingdom    64.511
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [195]:
g7_pop.iloc[[-1,0,3]]

United States    318.523
Canada            35.467
Italy             60.665
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [196]:
g7_pop['Canada':'Italy'] #printing from canada to italy excluding other elements in the list

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
Name: GEOGRAPHICAL POPULATION, dtype: float64

# Conditional Selection(boolean arrays)

In [197]:
#The applied boolean arrays for numpy can be applied to pandas series as well
g7_pop

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [198]:
g7_pop>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: GEOGRAPHICAL POPULATION, dtype: bool

In [199]:
g7_pop[g7_pop>70]

Germany           80.940
Japan            127.061
United States    318.523
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [200]:
g7_pop.mean()

107.30257142857144

In [201]:
g7_pop.mode() #Highest value

0     35.467
1     60.665
2     63.951
3     64.511
4     80.940
5    127.061
6    318.523
dtype: float64

In [202]:
g7_pop.median()

64.511

In [203]:
g7_pop.var()

9457.556639952383

In [204]:
g7_pop.std()

97.24996987121581

In [205]:
g7_pop[['Italy','France']]

Italy     60.665
France    63.951
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [206]:
g7_pop.iloc[[0,1]]

Canada    35.467
France    63.951
Name: GEOGRAPHICAL POPULATION, dtype: float64

In [207]:
g7_pop>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: GEOGRAPHICAL POPULATION, dtype: bool

In [208]:
g7_pop.log

AttributeError: 'Series' object has no attribute 'log'

In [ ]:
g7_pop[(g7_pop > g7_pop.mean()- g7_pop.std()/2)|(g7_pop>g7_pop.mean()+g7_pop.std()/2)]

In [ ]:
g7_pop

In [ ]:
g7_pop.mean()

In [ ]:
np.log(g7_pop)

In [ ]:
g7_pop

In [ ]:
data=pd.read_csv(r"C:\Users\khato\Downloads\archive(5)\countries of the world.csv")

In [ ]:
data

In [213]:
df=pd.DataFrame({
    'Population':[35.467,63.951,80.94,60.665,127.061,64.511,318.523],
    'GDP':[
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area':[
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI':[
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent':[
        
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
},columns=['Population','GDP','Surface Area','HDI','Continent'])

In [214]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [215]:
df.index=[     #Here we are assigning the countries to index values
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States'
]

In [216]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [217]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [218]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [219]:
df.size

35

In [220]:
df.shape

(7, 5)

In [221]:
df.describe() #Statistics of the data 

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [222]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [223]:
df.info

<bound method DataFrame.info of                 Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America>

In [224]:
df.dtypes.value_counts() #which variables has how many values it indicates


float64    2
int64      2
object     1
dtype: int64

# Indexing,Selection and Slicing

Individual column can be selected with regular indexing.Each column is represented as a Series:

In [225]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [226]:
df['Continent']

Canada            America
France             Europe
Germany            Europe
Italy              Europe
Japan                Asia
United Kingdom     Europe
United States     America
Name: Continent, dtype: object

In [227]:
df['HDI']

Canada            0.913
France            0.888
Germany           0.916
Italy             0.873
Japan             0.891
United Kingdom    0.907
United States     0.915
Name: HDI, dtype: float64

In [228]:
df['GDP']

Canada             1785387
France             2833687
Germany            3874437
Italy              2167744
Japan              4602367
United Kingdom     2950039
United States     17348075
Name: GDP, dtype: int64

In [229]:
df['Surface Area']

Canada            9984670
France             640679
Germany            357114
Italy              301336
Japan              377930
United Kingdom     242495
United States     9525067
Name: Surface Area, dtype: int64

In [230]:
df[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

Note that the index of the returned  Series is the same as the DataFrame one.And its name is the name of the column.If you're  working on the notebook and want to see a more  DataFrame-like format you can use the to_frame method:

In [231]:
df['Population'].to_frame()

Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

In [232]:
df['GDP'].to_frame()

GDP
Canada           1785387
France           2833687
Germany          3874437
Italy            2167744
Japan            4602367
United Kingdom   2950039
United States   17348075

In [233]:
df[['Population','GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [234]:
df[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

Row level selection works better  with loc and iloc which are recommended over regular "direct slicing"(df[:])

In [235]:
df.loc['Italy'] #for specific column if u wanna know information regarding ech field

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [236]:
df.loc['United Kingdom'] 

Population       64.511
GDP             2950039
Surface Area     242495
HDI               0.907
Continent        Europe
Name: United Kingdom, dtype: object

### 

In [237]:
df[1:3]

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [238]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [239]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [240]:
df.loc['France':'Italy',"Population"]

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [241]:
df.loc['France':'Italy','GDP']

France     2833687
Germany    3874437
Italy      2167744
Name: GDP, dtype: int64

In [242]:
df.iloc[[0,1,-1]]

Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [243]:
df.iloc[1:3,[0,3]]

Population    HDI
France       63.951  0.888
Germany      80.940  0.916

Recommended: Always ues loc or iloc to reduce ambiguity,specially with DataFramess with numeric index

In [244]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [245]:
df['Population']>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [246]:
df.loc[df['Population']>70]

Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [247]:
df.loc[df['Population']>70,'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

The boolean matching is done at index level,so you  can filter by any row,as long as it contains the right indexes.Columns selection still works as expected

In [248]:
df.loc[df['Population']>70,'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [249]:
df.drop(['Population'],axis=1)

GDP  Surface Area    HDI Continent
Canada           1785387       9984670  0.913   America
France           2833687        640679  0.888    Europe
Germany          3874437        357114  0.916    Europe
Italy            2167744        301336  0.873    Europe
Japan            4602367        377930  0.891      Asia
United Kingdom   2950039        242495  0.907    Europe
United States   17348075       9525067  0.915   America

In [250]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [251]:
df.drop(['Canada'])

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [252]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [253]:
data=df.drop(columns=['Population','HDI'],axis='columns')

In [254]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [255]:
data

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [256]:
df.drop(['Italy','France'],axis=0)

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

All these drop methods returns a new dataframe .if u like to modify 'in place' u can use  

In [258]:
crises=pd.Series([-1_000_000,-0.3],index=['GDP','HDI'])

In [259]:
crises

GDP   -1000000.0
HDI         -0.3
dtype: float64

In [260]:
df[['GDP','HDI']] + crises

GDP    HDI
Canada            785387.0  0.613
France           1833687.0  0.588
Germany          2874437.0  0.616
Italy            1167744.0  0.573
Japan            3602367.0  0.591
United Kingdom   1950039.0  0.607
United States   16348075.0  0.615

# Modifying Data

# It is simple and intuitive ,U can add columns or replace values for columns  witout issues:

In [261]:
langs=pd.Series(
['French','German','Italian'],
index=['France','Germany','Italy'],
name='Language')

In [262]:
langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: object

In [263]:
data

GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [264]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [269]:
df['Language']=langs  #Adding a column to the table

In [270]:
df

Population       GDP  Surface Area    HDI Continent Language  \
Canada              35.467   1785387       9984670  0.913   America      NaN   
France              63.951   2833687        640679  0.888    Europe   French   
Germany             80.940   3874437        357114  0.916    Europe   German   
Italy               60.665   2167744        301336  0.873    Europe  Italian   
Japan              127.061   4602367        377930  0.891      Asia      NaN   
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN   
United States      318.523  17348075       9525067  0.915   America      NaN   

                 Coffee  
Canada              NaN  
France           French  
Germany          German  
Italy           Italian  
Japan               NaN  
United Kingdom      NaN  
United States       NaN

In [277]:
df.drop(['Coffee'],axis=1)

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

# Rename a column

In [282]:
df.rename(
columns={
    'HDI':'Human Develpoment Index',
    'Annual Popcorn Consumpton':'APC'
}, index={
    'United States':'USA',
    'United Kingdom':'UK',
    'Argentina':'AR'
})

Population       GDP  Surface Area  Human Develpoment Index  \
Canada       35.467   1785387       9984670                    0.913   
France       63.951   2833687        640679                    0.888   
Germany      80.940   3874437        357114                    0.916   
Italy        60.665   2167744        301336                    0.873   
Japan       127.061   4602367        377930                    0.891   
UK           64.511   2950039        242495                    0.907   
USA         318.523  17348075       9525067                    0.915   

        Continent Language   Coffee  
Canada    America      NaN      NaN  
France     Europe   French   French  
Germany    Europe   German   German  
Italy      Europe  Italian  Italian  
Japan        Asia      NaN      NaN  
UK         Europe      NaN      NaN  
USA       America      NaN      NaN

In [285]:
df=df.drop(['Coffee'],axis=1)

In [287]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [288]:
df.rename(index=str.upper)

Population       GDP  Surface Area    HDI Continent Language
CANADA              35.467   1785387       9984670  0.913   America      NaN
FRANCE              63.951   2833687        640679  0.888    Europe   French
GERMANY             80.940   3874437        357114  0.916    Europe   German
ITALY               60.665   2167744        301336  0.873    Europe  Italian
JAPAN              127.061   4602367        377930  0.891      Asia      NaN
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe      NaN
UNITED STATES      318.523  17348075       9525067  0.915   America      NaN

In [290]:
df.rename(index=lambda x:x.lower()) #Anoetr method for replacing in loxwer case

Population       GDP  Surface Area    HDI Continent Language
canada              35.467   1785387       9984670  0.913   America      NaN
france              63.951   2833687        640679  0.888    Europe   French
germany             80.940   3874437        357114  0.916    Europe   German
italy               60.665   2167744        301336  0.873    Europe  Italian
japan              127.061   4602367        377930  0.891      Asia      NaN
united kingdom      64.511   2950039        242495  0.907    Europe      NaN
united states      318.523  17348075       9525067  0.915   America      NaN

In [306]:
df['Language']=langs

In [307]:
df

Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [308]:
df.drop(columns='Language', inplace=True) #in place will drop the column permanently and update the table

In [309]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [310]:
df.rename(index=str.upper)

Population       GDP  Surface Area    HDI Continent
CANADA              35.467   1785387       9984670  0.913   America
FRANCE              63.951   2833687        640679  0.888    Europe
GERMANY             80.940   3874437        357114  0.916    Europe
ITALY               60.665   2167744        301336  0.873    Europe
JAPAN              127.061   4602367        377930  0.891      Asia
UNITED KINGDOM      64.511   2950039        242495  0.907    Europe
UNITED STATES      318.523  17348075       9525067  0.915   America

In [311]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

# Dropping Columns

In [313]:
df.drop(columns='Language',inplace=True) #Giving error because the column have a;ready been drop peranentky it can't be retrieve


KeyError: "['Language'] not found in axis"

# Adding Values

In [317]:
df.append(pd.Series
         ({
             'Population':3,
             'GDP':5
         },name='China'
         ))

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America
China                3.000         5.0           NaN    NaN       NaN

In [322]:
df.drop('China', inplace=True)

KeyError: "['China'] not found in axis"

In [323]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [326]:
df.append(pd.Series({
          'HDI':0.43,
          'Continent':'China'
},name="China"))

Population         GDP  Surface Area    HDI Continent
Canada              35.467   1785387.0     9984670.0  0.913   America
France              63.951   2833687.0      640679.0  0.888    Europe
Germany             80.940   3874437.0      357114.0  0.916    Europe
Italy               60.665   2167744.0      301336.0  0.873    Europe
Japan              127.061   4602367.0      377930.0  0.891      Asia
United Kingdom      64.511   2950039.0      242495.0  0.907    Europe
United States      318.523  17348075.0     9525067.0  0.915   America
China                  NaN         NaN           NaN  0.430     China

In [333]:
df.drop("China", axis=0)

KeyError: "['China'] not found in axis"

In [331]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [334]:
df[['Population','GDP']]

Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

# More Radical Index

In [335]:
df.reset_index()

index  Population       GDP  Surface Area    HDI Continent
0          Canada      35.467   1785387       9984670  0.913   America
1          France      63.951   2833687        640679  0.888    Europe
2         Germany      80.940   3874437        357114  0.916    Europe
3           Italy      60.665   2167744        301336  0.873    Europe
4           Japan     127.061   4602367        377930  0.891      Asia
5  United Kingdom      64.511   2950039        242495  0.907    Europe
6   United States     318.523  17348075       9525067  0.915   America

In [336]:
df['GDP']/df['Population']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
dtype: float64

In [337]:
df['GDP per capital']=df['GDP']/df['Population']

In [338]:
df['GDP per capital']

Canada            50339.385908
France            44310.284437
Germany           47868.013343
Italy             35733.025633
Japan             36221.712406
United Kingdom    45729.239975
United States     54464.120330
Name: GDP per capital, dtype: float64

In [339]:
df

Population       GDP  Surface Area    HDI Continent  \
Canada              35.467   1785387       9984670  0.913   America   
France              63.951   2833687        640679  0.888    Europe   
Germany             80.940   3874437        357114  0.916    Europe   
Italy               60.665   2167744        301336  0.873    Europe   
Japan              127.061   4602367        377930  0.891      Asia   
United Kingdom      64.511   2950039        242495  0.907    Europe   
United States      318.523  17348075       9525067  0.915   America   

                GDP per capital  
Canada             50339.385908  
France             44310.284437  
Germany            47868.013343  
Italy              35733.025633  
Japan              36221.712406  
United Kingdom     45729.239975  
United States      54464.120330

# Statistical Information

In [340]:
df.head()

Population      GDP  Surface Area    HDI Continent  GDP per capital
Canada       35.467  1785387       9984670  0.913   America     50339.385908
France       63.951  2833687        640679  0.888    Europe     44310.284437
Germany      80.940  3874437        357114  0.916    Europe     47868.013343
Italy        60.665  2167744        301336  0.873    Europe     35733.025633
Japan       127.061  4602367        377930  0.891      Asia     36221.712406

In [341]:
df.describe()

Population           GDP  Surface Area       HDI  GDP per capital
count    7.000000  7.000000e+00  7.000000e+00  7.000000         7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429     44952.254576
std     97.249970  5.494020e+06  4.576187e+06  0.016592      6954.983875
min     35.467000  1.785387e+06  2.424950e+05  0.873000     35733.025633
25%     62.308000  2.500716e+06  3.292250e+05  0.889500     40265.998421
50%     64.511000  2.950039e+06  3.779300e+05  0.907000     45729.239975
75%    104.000500  4.238402e+06  5.082873e+06  0.914000     49103.699626
max    318.523000  1.734808e+07  9.984670e+06  0.916000     54464.120330

In [342]:
population=df['Population']

In [343]:
population

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [344]:
population.min()

35.467

In [345]:
population.max()

318.523

In [346]:
population.sum()

751.118

In [347]:
population.sum()/len(population)

107.30257142857144

In [349]:
len(population) #total no.of the rows of population

7

In [350]:
population.std()

97.24996987121581

In [351]:
population.mean()

107.30257142857144

In [352]:
population.mode()

0     35.467
1     60.665
2     63.951
3     64.511
4     80.940
5    127.061
6    318.523
dtype: float64

In [353]:
population.mode()

0     35.467
1     60.665
2     63.951
3     64.511
4     80.940
5    127.061
6    318.523
dtype: float64

In [358]:
population.quantile()

64.511

In [360]:
population.quantile([.2,.4,.6,.8,.12])

0.20     61.32220
0.40     64.17500
0.60     74.36840
0.80    117.83680
0.12     53.60956
Name: Population, dtype: float64

In [361]:
import numpy as np

In [362]:
import pandas as pd

In [364]:
import matplotlib.pyplot as plt
%matplotlib inline

In [365]:
pd.DataFrame(data=[None],
            index=[None],
            columns=[None])

NaN
NaN  None