In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Array in NumPy

In [10]:
X=np.array([[1,5],[3,45]])

In [11]:
print(X)

[[ 1  5]
 [ 3 45]]


In [12]:
X.shape

(2, 2)

In [13]:
X.ndim

2

In [9]:
X.size

4

# Vectors In NumPy

In [14]:
v1=np.array([1,5])

In [15]:
v1

array([1, 5])

In [16]:
v1.shape

(2,)

In [17]:
v2=v1.shape

In [18]:
v2

(2,)

In [30]:
v2=v1.reshape((1,2))

In [31]:
v2.reshape

<function ndarray.reshape>

In [32]:
v3=v2.reshape((1,2))

In [33]:
v3

array([[1, 5]])

In [34]:
v2

array([[1, 5]])

# Flatten Vector

In [35]:
v1+v2

array([[ 2, 10]])

In [36]:
v1+v2+v3

array([[ 3, 15]])

In [37]:
v4=v2.flatten()

In [38]:
v4

array([1, 5])

# Common Matrices

In [39]:
I3=np.eye(3)

In [40]:
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
I1=np.eye(10)
I1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
a=np.zeros([2,4]) #2 rows 4 columns

In [47]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a2=np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

# Matrix Operation

In [54]:
M1=np.array([[1,5],[2,4]])
M2=np.array([[2,-3],[0,9]])
M3=np.array([[1,2,6],[3,7,9]])
M4=np.array([[2,0,-1],[2,5,0]])
M5=np.array([[1,2,3],[4,5,6]])

In [60]:
np.dot(M1,M2)

array([[ 2, 42],
       [ 4, 30]])

In [61]:
print(M1)

[[1 5]
 [2 4]]


In [62]:
print(M1@M2)

[[ 2 42]
 [ 4 30]]


In [65]:
np.dot(M3.T,M4) #  .T is the transpose of the matrix

array([[ 8, 15, -1],
       [18, 35, -2],
       [30, 45, -6]])

# MATRIX OPERATION

In [67]:
np.amax(M1)

5

In [68]:
np.amax(M1,axis=1)

array([5, 4])

In [69]:
M1

array([[1, 5],
       [2, 4]])

In [70]:
np.argmax((M1))

1

In [75]:
np.argmin((M1))

0

In [76]:
M3

array([[1, 2, 6],
       [3, 7, 9]])

In [77]:
M1


array([[1, 5],
       [2, 4]])

In [78]:
np.amin(M1,axis=1)

array([1, 2])

In [79]:
np.sum(M1)

12

In [83]:
np.sum(M1,axis=0)

array([3, 9])

# Adding new columns and rows 

In [87]:
np.vstack((M1,M2)) #Adding vertical stack

array([[ 1,  5],
       [ 2,  4],
       [ 2, -3],
       [ 0,  9]])

In [88]:
np.hstack((M2,M3)) #Adding horizontal stack 

array([[ 2, -3,  1,  2,  6],
       [ 0,  9,  3,  7,  9]])

# Element-wise Matrix Operation

In [91]:
z=np.array([[1,4,9],[16,25,36]])

z

array([[ 1,  4,  9],
       [16, 25, 36]])

# Indexing and Slicing

In [92]:
M3

array([[1, 2, 6],
       [3, 7, 9]])

In [93]:
M3[0]

array([1, 2, 6])

In [95]:
M4[1]

array([2, 5, 0])

In [96]:
M3[:,-1]

array([6, 9])

# Creating Random Matrixes 

In [97]:
X=np.random.random((1,2))
Y=np.random.random((2,3))

In [98]:
X

array([[0.17097007, 0.26923787]])

In [99]:
Y

array([[0.33367711, 0.52017241, 0.99580154],
       [0.06749141, 0.57850426, 0.37492366]])

In [101]:
np.dot(X,Y)

array([[0.07522004, 0.24468917, 0.27119591]])

# Euclidean Distance

In [102]:
def distanceSlow(X,Z=None):
    if Z is None:
        Z=X
        n,d=X.shape #dimension of X
        m=Z.shape[0]
        D=np.zeros((n,m))
        for i in range(n):
            for j in range(m):
                D[i,j]=0.0
                for k in range(d):
                    D[i,j]=D[i,j]+(X[i,k]-Z[j,k])**2
                D[i,j]=np.sqrt(D[i,j])
        return D
    
    
X=np.random.rand(400,100)
%time Dslow=distanceSlow(X)                

Wall time: 45.8 s


In [105]:
def innerproduct(X,Z=None):
    %time Dslow=distanceSlow(X)
    

In [106]:
def distance(X,Z=None):
    if Z is None:
        Z=X